<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category  Ced
 * @package   Ced_Fruugo
 * @author    CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license   http://cedcommerce.com/license-agreement.txt
 */
?>
<div class="accordion">
    <div class="entry-edit form-inline">
        <div class="section-config">
            <div class="entry-edit-head">
                <div class="entry-edit-head admin__collapsible-block">
                    <span class="entry-edit-head-link" id="ced-support-link"></span> <a
                            onclick="Fieldset.toggleCollapse('ced-support','');return false;"
                            href="#ced-support-link" id="ced-support-head" class="">Cedcommerce
                        Support</a>
                </div>
            </div>
            <fieldset id="ced-support" class="admin__collapsible-block"
                      style="display: none;border:0 ">
                <ul>
                    <a target="_blank"
                       href="https://cedcommerce.com/magento-2-extensions/fruugo-magento-2-integration">Fruugo
                        Integration Knowledge base
                    </a>
                </ul>
            </fieldset>
            <script type="text/javascript">//&lt;![CDATA[
                require(['prototype'], function () {
                    Fieldset.applyCollapse('ced-support');
                });
                //]]&gt;</script>
        </div>
        <div class="section-config">
            <div class="entry-edit-head">
                <div class="entry-edit-head admin__collapsible-block">
                    <span class="entry-edit-head-link" id="documentation-link"></span>
                    <a onclick="Fieldset.toggleCollapse('documentation','');return false;"
                       href="#documentation-link" id="documentation-head" class="">Documentation</a>
                </div>
            </div>
            <fieldset id="documentation" class="admin__collapsible-block"
                      style="display: none;border:0px">
                <ul>
                    <a target="_blank"
                       href="https://docs.cedcommerce.com/magento-2/fruugo-magento-2-integration-guide-0-0-1">Fruugo
                        Integration Extension User Guide By CedCommerce</a>
                </ul>
            </fieldset>
            <script type="text/javascript">//&lt;![CDATA[
                require(['prototype'], function () {
                    Fieldset.applyCollapse('documentation');
                });
                //]]&gt;
            </script>
        </div>
        <!--<div class="section-config">
            <div class="entry-edit-head">
                <div class="entry-edit-head admin__collapsible-block">
                    <span class="entry-edit-head-link" id="fruugo-video-link"></span> <a
                            onclick="Fieldset.toggleCollapse('fruugo-video','');return false;"
                            href="#fruugo-video-link" id="fruugo-video-head" class="">Integration
                        Video from Fruugo.com</a>
                </div>
            </div>
            <fieldset id="fruugo-video" class="admin__collapsible-block"
                      style="display: none;border:0px">
                <div class="admin__data-grid-wrap admin__data-grid-wrap-static">
                    <ul style="padding-left: 20px">
                        <li><a target="_blank" href="https://www.youtube.com/watch?v=DJXgKgqqCLI&feature=youtu.be">Integration
                                Process Inlioduction of Fruugo.com</a></li>
                        <li><a target="_blank" href="https://youtu.be/e0jg73m1L_I">API
                                Overview</a></li>
                        <li><a target="_blank" href="https://youtu.be/aKEF2kBNs6A">Merchant
                                Basic Information Setup at Partner Portal</a></li>
                        <li><a target="_blank" href="https://youtu.be/MVHCjB7jhww">Products
                                API call test</a></li>
                        <li><a target="_blank" href="https://youtu.be/4UsuZux4vug">Products
                                Overview</a></li>
                        <li><a target="_blank" href="https://youtu.be/MVHCjB7jhww">Products
                                API call test</a></li>
                        <li><a target="_blank" href="https://youtu.be/q1rW7wFzBAg">Orders
                                Setup</a></li>
                        <li><a target="_blank" href="https://youtu.be/7ZUjRQLTxUw">Returns
                                Setup </a></li>
                        <li><a target="_blank"
                               href="https://developer.fruugo.com/v1.0/page/integration-videos">Integration
                                Videos </a></li>
                    </ul>
                </div>
            </fieldset>
            <script type="text/javascript">//&lt;![CDATA[
                require(['prototype'], function(){Fieldset.applyCollapse('fruugo-video');});
                //]]&gt;</script>
        </div>-->
        <!--Links for fruugo documentations-->
        <!--<div class="section-config">
            <div class="entry-edit-head">
                <div class="entry-edit-head admin__collapsible-block">
                    <span class="entry-edit-head-link" id="fruugo-docs-link"></span> <a
                            onclick="Fieldset.toggleCollapse('fruugo-docs','');return false;"
                            href="#fruugo-docs-link" id="fruugo-docs-head" class="">Integration
                        Documents from Fruugo.com</a>
                </div>
            </div>
            <fieldset id="fruugo-docs" class="admin__collapsible-block"
                      style="display: none;border:0px">
                <div class="admin__data-grid-wrap admin__data-grid-wrap-static">
                    <ul style="padding-left: 20px">
                        <li>
                            <a target="_blank" href="https://marketplace.fruugo.com/knowledgebase/articles/Article/Defining-Attributes">
                                How to Define Attributes For Item Setup?
                            </a>
                        </li>
                        <li>
                            <a target="_blank" href="https://marketplace.fruugo.com/knowledgebase/articles/File_Download/Selecting-The-Best-Category-For-An-Item">
                                How to Select The Best Category For An Item?
                            </a>
                        </li>
                        <li>
                            <a target="_blank" href="https://marketplace.fruugo.com/knowledgebase/articles/Article/How-To-Set-Up-A-Variant-Group">
                                How To Set Up A Variant Group/Products?
                            </a>
                        </li>
                        <li>
                            <a target="_blank" href="https://marketplace.fruugo.com/knowledgebase/articles/File_Download/Current-Taxware-Tax-Codes-for-the-Fruugo-Marketplace">
                                How to Choose Current Tax Codes For The Fruugo Marketplace?
                            </a>
                        </li>
                    </ul>
                </div>
            </fieldset>
            <script type="text/javascript">//&lt;![CDATA[
                require(['prototype'], function(){Fieldset.applyCollapse('fruugo-docs');});
                //]]&gt;</script>
        </div>-->
        <!--codes for to show Different contact medium-->
        <div class="section-config">
            <div class="entry-edit-head">
                <div class="entry-edit-head admin__collapsible-block">
                    <span class="entry-edit-head-link" id="fruugo-docs-link"></span>
