<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Adminhtml\Product\Edit\Tab\Price\Tier */
$element = $block->getElement();

?>
<?php $_htmlId      = 'configAttributes' ?>
<?php $_htmlClass   = 'configAttributeClass' ?>
<?php $_htmlName    = 'variant_attributes' ?>
<?php $_readonly    = false ?>

<fieldset class="fieldset">
        <div class="field" id="attribute-<?php /* @escapeNotVerified */ echo $_htmlId?>-container" data-attribute-code="<?php /* @escapeNotVerified */ echo $_htmlId?>"
        >
            <div class="control">
                <table class="admin__control-table tiers_table" id="tiers_table">
                    <thead>
                    <tr>
                        <th class="col-customer-group"><?php /* @escapeNotVerified */ echo __('Fruugo Attribute') ?></th>
                        <th class="col-qty required"><?php /* @escapeNotVerified */ echo __('Magento Catalog Attribute') ?></th>
                        <th class="col-delete"><?php /* @escapeNotVerified */ echo __('Action') ?></th>
                    </tr>
                    </thead>
                    <tbody id="<?php /* @escapeNotVerified */ echo $_htmlId ?>_container"></tbody>
                    <tfoot>
                    <tr>
                        <td colspan="4" class="col-actions-add"><?php echo $block->getChildHtml('add_button') ?></td>
                    </tr>
                    </tfoot>
                </table>

                <script>
                    require([
                        'mage/template',
                        "prototype",
                        "mage/adminhtml/form"
                    ], function (mageTemplate) {

//<![CDATA[
                        var configAttributeRowTemplate = '<tr>'
                            + '<td>'
                            + '<input type="hidden" name="<?php echo $_htmlName ?>[<%- data.index %>][fruugo_attribute_type]" id="config_attribute_row_<%- data.index %>_fruugo_attribute_type"" />'
                            +'<select onclick="return configAttributeControl.setFruugoAttributeType(this, <%- data.index %>);" class="<?php echo $_htmlClass ?> custgroup required-entry" name="<?php echo $_htmlName ?>[<%- data.index %>][fruugo_attribute_name]" id="config_attribute_row_<%- data.index %>_fruugo_attribute">'
                            <?php
                            foreach ($this->getFruugoConfigAttributes() as $code => $attribute){
                            ?>
                            + '<option value="<?php echo $code ?>" attribute_type="<?php echo $attribute['fruugo_attribute_type'] ?>"><?php echo __($attribute['fruugo_attribute_name']) ?></option>'
                            <?php }   ?>

                            + '</select></td>'
                            + '<td> <select class="<?php echo $_htmlClass ?> required_magento_attr required-entry" name="<?php echo $_htmlName ?>[<%- data.index %>][magento_attribute_code]" id="config_attribute_row_<%- data.index %>_magento_attr">'
                            <?php
                            foreach ($this->getMagentoAttributes() as $_groupId=>$_groupName): ?>
                            + '<option value="<?php echo $_groupId ?>"><?php echo __($_groupName) ?></option>'
                            <?php endforeach ?>
                            + '</select>'
                            + ' </td>'

                            + '<td class="col-delete"><input type="hidden" name="<?php /* @escapeNotVerified */ echo $_htmlName ?>[<%- data.index %>][delete]" class="delete" value="" id="config_attribute_row_<%- data.index %>_delete" />'
                            + '<button title="<?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Delete Tier')); ?>" type="button" class="action- scalable delete icon-btn delete-product-option" id="config_attribute_row_<%- data.index %>_delete_button" onclick="return configAttributeControl.deleteItem(event);">'
                            + '<span><?php /* @escapeNotVerified */ echo __("Delete") ?></span></button></td>'
                            + '</tr>';

                        var configAttributeControl = {
                            template: mageTemplate(configAttributeRowTemplate),
                            itemsCount: 0,
                            addItem : function () {
                                <?php if ($_readonly): ?>
                                if (arguments.length < 3) {
                                    return;
                                }
                                <?php endif; ?>
                                var data = {
                                    fruugo_attribute: '',
                                    magento_attr: '',
                                    required: '',
                                    fruugo_attribute_type: '',
                                    index: this.itemsCount++
                                };

                                if(arguments.length >= 4) {
                                    data.fruugo_attribute = arguments[0];
                                    data.magento_attr      = arguments[1];
                                    data.fruugo_attribute_type      = arguments[2];
                                    data.required        = arguments[3];
                                }


                                Element.insert($('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container'), {
                                    bottom : this.template({
                                        data: data
                                    })
                                });
                                $('config_attribute_row_' + data.index + '_fruugo_attribute').value = data.fruugo_attribute;
                                $('config_attribute_row_' + data.index + '_magento_attr').value    = data.magento_attr;
                                $('config_attribute_row_' + data.index + '_fruugo_attribute_type').value    = data.fruugo_attribute_type;

                                <?php /*if ($block->isShowWebsiteColumn() && !$block->isAllowChangeWebsite()):?>
                        var wss = $('config_attribute_row_' + data.index + '_website');
                        var txt = wss.options[wss.selectedIndex].text;

                        wss.insert({after:'<span class="website-name">' + txt + '</span>'});
                        wss.hide();
                        <?php endif;*/ ?>

                                if (data.readOnly == '1') {
                                    ['website', 'cust_group', 'qty', 'price', 'delete'].each(function(idx){
                                        $('config_attribute_row_'+data.index+'_'+idx).disabled = true;
                                    });
                                    $('config_attribute_row_'+data.index+'_delete_button').hide();
                                }

                                <?php if ($_readonly): ?>
                                $('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container').select('input', 'select').each(this.disableElement);
                                $('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container').up('table').select('button').each(this.disableElement);
                                <?php else: ?>
                                $('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container').select('input', 'select').each(function(el){ Event.observe(el, 'change', el.setHasChanges.bind(el)); });
                                <?php endif; ?>
                            },
                            disableElement: function(el) {
                                el.disabled = true;
                                el.addClassName('disabled');
                            },
                            deleteItem: function(event) {
                                var tr = Event.findElement(event, 'tr');
                                if (tr) {
                                    Element.select(tr, '.delete').each(function(elem){elem.value='1'});
                                    Element.select(tr, ['input', 'select']).each(function(elem){elem.hide()});
                                    Element.hide(tr);
                                    Element.addClassName(tr, 'no-display template');
                                }
                                return false;
                            },
                            setFruugoAttributeType: function(e, index) {
                                var attributeType = e.options[e.selectedIndex].getAttribute('attribute_type');
                                $('config_attribute_row_' + index + '_fruugo_attribute_type').value    = attributeType;
                            }
                        };
                        <?php  foreach ($this->getFruugoAttributeValuesMapping() as $_item):
                        ?>
                        configAttributeControl.addItem('<?php echo $_item['fruugo_attribute_name'] ?>', '<?php echo $_item['magento_attribute_code'] ?>','<?php echo $_item['fruugo_attribute_type'] ?>', false);
                        <?php endforeach; ?>
                        <?php if ($_readonly): ?>
                        $('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container').up('table').select('button')
                            .each(requiredAttributeControl.disableElement);
                        <?php endif; ?>

                        window.configAttributeControl = configAttributeControl;
//]]>

                    });
                </script>
            </div>
        </div>
