<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Adminhtml\Product\Edit\Tab\Price\Tier */
$element = $block->getElement();

?>
<?php $_htmlId      = 'requiredAttributes' ?>
<?php $_htmlClass   = 'requiredAttributeClass' ?>
<?php $_htmlName    = 'required_attributes' ?>
<?php $_readonly    = false ?>
<div class="field" id="attribute-<?php /* @escapeNotVerified */ echo $_htmlId?>-container" data-attribute-code="<?php /* @escapeNotVerified */ echo $_htmlId?>"
     >
    <div class="control">
        <table class="admin__control-table tiers_table" id="tiers_table">
            <thead>
            <tr>
                <th class="col-customer-group"><?php /* @escapeNotVerified */ echo __('Fruugo Attribute') ?></th>
                <th class="col-qty required"><?php /* @escapeNotVerified */ echo __('Magento Catalog Attribute') ?></th>
                <th class="col-qty required"><?php /* @escapeNotVerified */ echo __('Default Value') ?></th>
                <th class="col-delete"><?php /* @escapeNotVerified */ echo __('Action') ?></th>
            </tr>
            </thead>
            <tbody id="<?php /* @escapeNotVerified */ echo $_htmlId ?>_container"></tbody>
            <tfoot>
            <tr>
                <td colspan="4" class="col-actions-add"><?php echo $block->getChildHtml('add_button') ?></td>
            </tr>
            </tfoot>
        </table>

        <script>
            require([
                'mage/template',
                "prototype",
                "mage/adminhtml/form"
            ], function (mageTemplate) {

//<![CDATA[
                var requiredAttributeRowTemplate = '<tr>'
                    + '<input type="hidden" value="0" name="<?php echo $_htmlName ?>[<%- data.index %>][required]" id="tier_price_row_<%- data.index %>_fruugo_required"" />'
                    + '<input type="hidden" name="<?php echo $_htmlName ?>[<%- data.index %>][fruugo_attribute_name]" id="tier_price_row_<%- data.index %>_fruugo_attribute_hidden"" />'
                    + '<input type="hidden" name="<?php echo $_htmlName ?>[<%- data.index %>][fruugo_attribute_type]" id="tier_price_row_<%- data.index %>_fruugo_attribute_type"" />'
                    + '<td><select onChange="return requiredAttributeControl.setFruugoAttributeType(this, <%- data.index %>);" class="<?php echo $_htmlClass ?> custgroup required-entry" name="<?php echo $_htmlName ?>[<%- data.index %>][fruugo_attribute_name]" id="tier_price_row_<%- data.index %>_fruugo_attribute">'

                    <?php
                    foreach ($this->getFruugoAttributes() as $optGroup){
                    $disable = '';
                    if($optGroup['label'] == 'Required Attributes'){
                        $disable = 'disabled="disabled"';
                    }
                    ?>
                    +'<optgroup <?php echo  $disable ?> label="<?php echo $optGroup['label'] ?> ">'
                    <?php
                    foreach ($optGroup['value'] as $_groupId=>$_groupName):
                    $attributeEnum = $_groupName['fruugo_attribute_enum'];
                    $attributeEnum = implode(',',array_map(
                        function($arg) {
                            return str_replace("\r", "", str_replace("\n", "", trim($arg)));
                        }, explode(',',$attributeEnum)));
                    $attributeEnum = addslashes($attributeEnum);
                    ?>
                    + '<option value="<?php echo $_groupId ?>" enum_val="<?php echo $attributeEnum; ?>" attribute_type="<?php echo $_groupName['fruugo_attribute_type'] ?>"><?php echo __($_groupName['fruugo_attribute_name']) ?></option>'
                    <?php endforeach
                    ?>
                    +'</optgroup>'
                    <?php  }
                    ?>
                    + '</select></td>'
                    + '<td> <select onChange="return requiredAttributeControl.showDefaultField(this, <%- data.index %>);"  class="<?php echo $_htmlClass ?> required_magento_attr required-entry" name="<?php echo $_htmlName ?>[<%- data.index %>][magento_attribute_code]" id="tier_price_row_<%- data.index %>_magento_attr">'
                    <?php foreach ($this->getMagentoAttributes() as $_groupId=>$_groupName): ?>
                    + '<option value="<?php echo $_groupId ?>" ><?php echo __($_groupName) ?></option>'
                    <?php endforeach ?>
                    + '</select>'
                    + ' </td>'
                    + '<td><input style="display:none;" type="text" name="<?php /* @escapeNotVerified */ echo $_htmlName ?>[<%- data.index %>][default]" value="" id="tier_price_row_<%- data.index %>_default_text" />'
                    + '<select  style="display:none;" class="<?php echo $_htmlClass ?> required_magento_attr" name="<?php echo $_htmlName ?>[<%- data.index %>][default]" id="tier_price_row_<%- data.index %>_default_select">'
                    + '</select>'
                    + '<td class="col-delete"><input type="hidden" name="<?php /* @escapeNotVerified */ echo $_htmlName ?>[<%- data.index %>][delete]" class="delete" value="" id="tier_price_row_<%- data.index %>_delete" />'
                    + '<button title="<?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Delete')); ?>" type="button" class="action- scalable delete icon-btn delete-product-option" id="tier_price_row_<%- data.index %>_delete_button" onclick="return requiredAttributeControl.deleteItem(event);">'
                    + '<span><?php /* @escapeNotVerified */ echo __("Delete") ?></span></button></td>'
                    + '</tr>';

                var requiredAttributeControl = {
                    template: mageTemplate(requiredAttributeRowTemplate),
                    itemsCount: 0,
                    addItem : function () {
                        <?php if ($_readonly): ?>
                        if (arguments.length < 5) {
                            return;
                        }
                        <?php endif; ?>
                        var data = {
                            fruugo_attribute: '',
                            magento_attr: '',
                            required: '',
                            fruugo_attribute_type: '',
                            index: this.itemsCount++,
                            default:''
                        };

                        if(arguments.length >= 5) {
                            data.fruugo_attribute = arguments[0];
                            data.magento_attr      = arguments[1];
                            data.fruugo_attribute_type      = arguments[2];
                            data.required        = arguments[3];
                            data.default = arguments[4];
                        }
                        /*if (arguments.length == 5) {
                            data.readOnly = arguments[4];
                        }*/

                        Element.insert($('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container'), {
                            bottom : this.template({
                                data: data
                            })
                        });
                        var fruugoAttribute = $('tier_price_row_' + data.index + '_fruugo_attribute');
                        var magentoAttribute = $('tier_price_row_' + data.index + '_magento_attr');
                        fruugoAttribute.value = data.fruugo_attribute;
                        magentoAttribute.value    = data.magento_attr;
                        $('tier_price_row_' + data.index + '_fruugo_attribute_type').value    = data.fruugo_attribute_type;


                        if(data.required==1) {
                            // $('tier_price_row_' + data.index + '_fruugo_attribute').disabled = true;
                            $('tier_price_row_' + data.index + '_delete_button').remove();
                            $('tier_price_row_' + data.index + '_fruugo_attribute').disabled = true;
                            $('tier_price_row_' + data.index + '_fruugo_attribute_hidden').value = data.fruugo_attribute;
                            $('tier_price_row_' + data.index + '_fruugo_required').value    = data.required;


                        }

                    <?php /*if ($block->isShowWebsiteColumn() && !$block->isAllowChangeWebsite()):?>
                        var wss = $('tier_price_row_' + data.index + '_website');
                        var txt = wss.options[wss.selectedIndex].text;

                        wss.insert({after:'<span class="website-name">' + txt + '</span>'});
                        wss.hide();
                        <?php endif;*/ ?>

                        /*if (data.readOnly == '1') {
                            ['website', 'cust_group', 'qty', 'price', 'delete'].each(function(idx){
                                $('tier_price_row_'+data.index+'_'+idx).disabled = true;
                            });
                            $('tier_price_row_'+data.index+'_delete_button').hide();
                        }*/

                        <?php if ($_readonly): ?>
                        $('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container').select('input', 'select').each(this.disableElement);
                        $('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container').up('table').select('button').each(this.disableElement);
                        <?php else: ?>
                        $('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container').select('input', 'select').each(function(el){ Event.observe(el, 'change', el.setHasChanges.bind(el)); });
                        <?php endif; ?>

                        requiredAttributeControl.setFruugoAttributeType(fruugoAttribute, data.index);
                        if(data.default!=''){
                            var enumVal = fruugoAttribute.options[data.index].getAttribute('enum_val');
                            var text = $('tier_price_row_'+data.index+'_default_text');
                            var select = $('tier_price_row_'+data.index+'_default_select');
                            select.value = data.default;
                            text.value = data.default;

                            requiredAttributeControl.showDefaultField(magentoAttribute, data.index);
                        }

                    },
                    disableElement: function(el) {
                        el.disabled = true;
                        el.addClassName('disabled');
                    },
                    deleteItem: function(event) {
                        var tr = Event.findElement(event, 'tr');
                        if (tr) {
                            Element.select(tr, '.delete').each(function(elem){elem.value='1'});
                            Element.select(tr, ['input', 'select']).each(function(elem){elem.hide()});
                            Element.hide(tr);
                            Element.addClassName(tr, 'no-display template');
                        }
                        return false;
                    },
                    showDefaultField: function (e, index) {
                        var checkdefault = e.options[e.selectedIndex].getAttribute('value');
                        var text = $('tier_price_row_'+index+'_default_text');
                        var select = $('tier_price_row_'+index+'_default_select');

                        if(checkdefault == 'default'){
                            var fruugoAttribute = $('tier_price_row_' + index + '_fruugo_attribute');
                            var enumVal = fruugoAttribute.options[fruugoAttribute.selectedIndex].getAttribute('enum_val');
                            if(enumVal){
                                select.enable();
                                select.show();
                            }
                            else{
                                text.enable();
                                text.show();
                            }

                        }else{
                            select.hide();
                            text.hide();
                            select.disable();
                            text.disable();
                        }


                    },
                    setFruugoAttributeType: function(e, index) {
                        if(e.selectedIndex!=-1){
                            var attributeType = e.options[e.selectedIndex].getAttribute('attribute_type');
                            $('tier_price_row_' + index + '_fruugo_attribute_type').value    = attributeType;

                            var enumVal = e.options[e.selectedIndex].getAttribute('enum_val');
                            var text = $('tier_price_row_'+index+'_default_text');
                            var select = $('tier_price_row_'+index+'_default_select');
                            select.hide();
                            text.hide();
                            select.disable();
                            text.disable();

                            if(enumVal){
                                var values = enumVal.split(",");
                                while (select.options.length > 0) {
                                    select.remove(0);
                                }
                                for ( i=0; i<values.length; i++) {
                                    select.insert(new Element('option', {"value": values[i]}).update(values[i]));
                                }
                            }
                        }
                    }
                };
                <?php
                if(count($this->getFruugoAttributeValuesMapping())>0)
                foreach ($this->getFruugoAttributeValuesMapping() as $_item):
                $default = isset($_item['default'])?$_item['default']:'';
                ?>
                requiredAttributeControl.addItem('<?php echo $_item['fruugo_attribute_name'] ?>', '<?php echo $_item['magento_attribute_code'] ?>', '<?php echo $_item['fruugo_attribute_type'] ?>','<?php echo $_item['required'] ?>','<?php echo $default; ?>');

                <?php endforeach; ?>
                <?php if ($_readonly): ?>
                $('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container').up('table').select('button')
                    .each(requiredAttributeControl.disableElement);
                <?php endif; ?>

                window.requiredAttributeControl = requiredAttributeControl;
//]]>

            });
        </script>
    </div>
</div>